apiVersion: 3
dataDisplay:
  excludedFeatures: []
  noneValues:
  - none
  - unknown
  - null
  - NA
  sectionSep1: ' '
  sectionSep2: ':'
  textFormat: text-orig-full
docs:
  docRoot: "https://github.com/saulocantanhede/tfgreek2"
#  docRoot: "https://github.com"
  docBase: "https://github.com/saulocantanhede/tfgreek2/tree/main/docs"
  featureBase: "https://github.com/saulocantanhede/tfgreek2/tree/main/docs/features/<feature>.md"
  docPage: "about"
  featurePage : README
interfaceDefaults:
  fmt: text-orig-full # used by tf browser
provenanceSpec:
  corpus: Nestle 1904 Greek New Testament
  org: saulocantanhede
  repro: tfgreek2
  branch: main
  doi: 10.5281/zenodo.notyet
  moduleSpecs: []
  version: 0.5.5
  webBase: https://learner.bible/text/show_text/nestle1904/
  webHint: Show this on the website
  webLang: en
  webUrl: https://learner.bible/text/show_text/nestle1904/<1>/<2>/<3>
  webUrlLex: '{webBase}/word?version={version}&id=<lid>'
typeDisplay:
  sentence:
    label: '#{num}: {rule}'
    style: ''
  group:
    label: '#{num}: '
    style: ''
  wg:
    label: '#{num}: {role} {typ} {rule} {junction}'
    style: ""
    condense: true
  clause:
    label: '#{num}: {cls} {rule} {junction}'
    style: ''
    condense: true
  phrase:
    label: '#{num}: {function} {type} {rule} '
    style: ''
    condense: true
  subphrase:
    label: '#{num}: {function} {type} {rule} '
    style: ''
    condense: true
  verse:
    label: '{book} {chapter}:{verse}'
    style: ''
    condense: true
  word:
    base: true
writing: grc
