apiVersion: 3
dataDisplay:
  excludedFeatures: []
  noneValues:
  - none
  - unknown
  - null
  - NA
  sectionSep1: ' '
  sectionSep2: ':'
  textFormat: text-orig-full
docs:
  docBase: https://github.com/saulocantanhede/tfgreek2/tree/main/docs
  docPage: about
  docRoot: https://github.com/saulocantanhede/tfgreek2
  featureBase: https://github.com/saulocantanhede/tfgreek2/tree/main/docs/features/<feature>.md
  featurePage: README
interfaceDefaults:
  fmt: text-orig-full
provenanceSpec:
  branch: main
  corpus: Nestle 1904 Greek New Testament
  doi: 10.5281/zenodo.notyet
  moduleSpecs: []
  org: saulocantanhede
  repro: tfgreek2
  version: 0.5.6
  webBase: https://learner.bible/text/show_text/nestle1904/
  webHint: Show this on the website
  webLang: en
  webUrl: https://learner.bible/text/show_text/nestle1904/<1>/<2>/<3>
  webUrlLex: '{webBase}/word?version={version}&id=<lid>'
typeDisplay:
  clause:
    condense: true
    label: '{typ} {function} {rela} \\ {cls} {role} {junction}'
    style: ''
  group:
    label: '{typ} {function} {rela} \\ {type} {role} {rule}'
    style: ''
  phrase:
    condense: true
    label: '{typ} {function} {rela} \\ {type} {role} {rule}'
    style: ''
  sentence:
    label: '{typ} {function} {rela} \\ {role} {rule}'
    style: ''
  subphrase:
    label: '{typ} {function} {rela} \\ {type} {role} {rule}'
    style: ''
  verse:
    condense: true
    label: '{book} {chapter}:{verse}'
    style: ''
  wg:
    condense: true
    label: '{type} {role} {rule} {junction}'
    style: ''
  word:
    features:
    - lemma
    - sp
    featuresBare:
    - gloss
writing: grc
