apiVersion: 3
dataDisplay:
  excludedFeatures: []
  noneValues:
  - none
  - unknown
  - null
  - NA
  sectionSep1: ' '
  textFormat: text-orig-full
docs:
  docPage: about
  featureBase: '{docBase}/transcription.md'
  featurePage: '{docBase}/features/<feature>.md'
interfaceDefaults:
  fmt: text-orig-full
provenanceSpec:
  corpus: Nestle 1904 Greek New Testament
  doi: 10.5281/zenodo.notyet
  moduleSpecs: []
  version: 0.5.5
  webBase: https://learner.bible/text/show_text/nestle1904/
  webHint: Show this on the website
  webLang: en
  webUrl: https://learner.bible/text/show_text/nestle1904/<1>/<2>/<3>
  webUrlLex: '{webBase}/word?version={version}&id=<lid>'
typeDisplay:
  sentence:
    label: '#{num}: {rule}'
    style: ''
  group:
    label: '#{num}: '
    style: ''
  wg:
    label: '#{num}: {type} {role} {rule} {junction}'
    style: ""
    condense: true
  clause:
    label: '#{num}: {cls} {rule} {junction}'
    style: ''
    condense: true
  phrase:
    label: '#{num}: {function} {role} {rule} {type}'
    style: ''
    condense: true
  verse:
    label: '{book} {chapter}:{verse}'
    style: ''
    condense: true
  word:
    base: true
writing: grc
